FROM node:16.20.0-alpine3.16

ARG NODE_ENV="development"

RUN mkdir -p ./client

WORKDIR /client

COPY package.json ./

RUN npm install

RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .

EXPOSE 3000

CMD npm start
