version: '3'
services:

  front-react:
    build:
      context: ./client
      dockerfile: Dockerfile-development

    environment:
      NODE_ENV: development
    depends_on:
      - server-dev
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "3000:3000"

  server-dev:
    build:
      context: ./server
      dockerfile: Dockerfile-development

    environment:
      NODE_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - db-dev
      - mongo-dev
    volumes:
      - ./server:/server
      - /server/node_modules


  mongo-dev:
    image: mongo:4.4.6-bionic
    ports:
      - "27017:27017"



  db-dev:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo-dev
    ports:
      - "5432:5432"

volumes:
  server-dev:
