const ACTION_TYPES = {
  //auth
  SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_ERROR: 'SIGN_IN_ERROR',
  //
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',
  //
  REFRESH_REQUEST: 'REFRESH_REQUEST',
  REFRESH_SUCCESS: 'REFRESH_SUCCESS',
  REFRESH_ERROR: 'REFRESH_ERROR',
  //
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_ERROR: 'LOGOUT_ERROR',
  //
  GET_AUTH_USER_REQUEST: 'GET_AUTH_USER_REQUEST',
  GET_AUTH_USER_SUCCESS: 'GET_AUTH_USER_SUCCESS',
  GET_AUTH_USER_ERROR: 'GET_AUTH_USER_ERROR',
  //users
  UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_ERROR: 'UPDATE_USER_ERROR',
  //
  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_ERROR: 'GET_USERS_ERROR',
  //tasks
  CREATE_TASK_REQUEST: 'CREATE_TASK_REQUEST',
  CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
  CREATE_TASK_ERROR: 'CREATE_TASK_ERROR',
  //
  GET_TASKS_REQUEST: 'GET_TASKS_REQUEST',
  GET_TASKS_SUCCESS: 'GET_TASKS_SUCCESS',
  GET_TASKS_ERROR: 'GET_TASKS_ERROR',
  //
  GET_TASK_REQUEST: 'GET_TASK_REQUEST',
  GET_TASK_SUCCESS: 'GET_TASK_SUCCESS',
  GET_TASK_ERROR: 'GET_TASK_ERROR',
  //
  UPDATE_TASK_REQUEST: 'UPDATE_TASK_REQUEST',
  UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',
  UPDATE_TASK_ERROR: 'UPDATE_TASK_ERROR',
  //
  DELETE_TASK_REQUEST: 'DELETE_TASK_REQUEST',
  DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
  DELETE_TASK_ERROR: 'DELETE_TASK_ERROR',
  //
  CLEAN_USER_ERROR: 'CLEAN_USER_ERROR',
  //
  CLEAN_ERROR: 'CLEAN_ERROR',
  //chats
  CREATE_MESSAGE_REQUEST: 'CREATE_MESSAGE_REQUEST',
  CREATE_MESSAGE_SUCCESS: 'CREATE_MESSAGE_SUCCESS',
  CREATE_MESSAGE_ERROR: 'CREATE_MESSAGE_ERROR',
  //
  GET_MESSAGES_REQUEST: 'GET_MESSAGES_REQUEST',
  GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
  GET_MESSAGES_ERROR: 'GET_MESSAGES_ERROR',
  //
  GET_CHATS_REQUEST: 'GET_CHATS_REQUEST',
  GET_CHATS_SUCCESS: 'GET_CHATS_SUCCESS',
  GET_CHATS_ERROR: 'GET_CHATS_ERROR',
  //
  CHOOSE_CURRENT_CHAT: 'CHOOSE_CURRENT_CHAT',
  // CHOOSE_CURRENT_CHAT_SUCCESS: 'CHOOSE_CURRENT_CHAT_SUCCESS',
  // CHOOSE_CURRENT_CHAT_ERROR: 'CHOOSE_CURRENT_CHAT_ERROR',
  //
  CLEAR_CHATS_SUCCESS: 'CLEAR_CHATS_SUCCESS',
  //
  CLEAR_CURRENT_CHAT: 'CLEAR_CURRENT_CHAT',
  //
  SET_IS_TYPING: 'SET_IS_TYPING',
  //
  SET_ONLINE_STATUS_REQUEST: 'SET_ONLINE_STATUS_REQUEST',
  SET_ONLINE_STATUS_ERROR: 'SET_ONLINE_STATUS_ERROR',
  SET_ONLINE_STATUS: 'SET_ONLINE_STATUS',
  //
  GET_ONLINE_USERS: 'GET_ONLINE_USERS',
  //
  SUBSCRIBE_CHATS_REQUEST: 'SUBSCRIBE_CHATS_REQUEST',
  SUBSCRIBE_CHATS_ERROR: 'SUBSCRIBE_CHATS_ERROR',
  //
  GET_ONLINE_USERS_REQUEST: 'GET_ONLINE_USERS_REQUEST',
  GET_ONLINE_USERS_ERROR: 'GET_ONLINE_USERS_ERROR',
  //
  START_TYPING_REQUEST: 'START_TYPING_REQUEST',
  START_TYPING_ERROR: 'START_TYPING_ERROR',
  STOP_TYPING_REQUEST: 'STOP_TYPING_REQUEST',
  STOP_TYPING_ERROR: 'STOP_TYPING_ERROR',
  //
  SET_SEEN_MESSAGE_REQUEST: 'SET_SEEN_MESSAGE_REQUEST',
  SET_SEEN_MESSAGE_SUCCESS: 'SET_SEEN_MESSAGE_SUCCESS',
  SET_SEEN_MESSAGE_ERROR: 'SET_SEEN_MESSAGE_ERROR',
};

export default ACTION_TYPES;
